/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'
import { Route as EcosystemIndexRouteImport } from './routes/ecosystem.index'
import { Route as EcosystemSlugRouteImport } from './routes/ecosystem.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemIndexRoute = EcosystemIndexRouteImport.update({
  id: '/ecosystem/',
  path: '/ecosystem/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemSlugRoute = EcosystemSlugRouteImport.update({
  id: '/ecosystem/$slug',
  path: '/ecosystem/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/ecosystem/$slug': typeof EcosystemSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/ecosystem/$slug': typeof EcosystemSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/capabilities': typeof CapabilitiesIndexRoute
  '/ecosystem': typeof EcosystemIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/ecosystem/$slug': typeof EcosystemSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/ecosystem/': typeof EcosystemIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/capabilities/$slug'
    | '/ecosystem/$slug'
    | '/insights/$slug'
    | '/work/$slug'
    | '/capabilities/'
    | '/ecosystem/'
    | '/insights/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/capabilities/$slug'
    | '/ecosystem/$slug'
    | '/insights/$slug'
    | '/work/$slug'
    | '/capabilities'
    | '/ecosystem'
    | '/insights'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/capabilities/$slug'
    | '/ecosystem/$slug'
    | '/insights/$slug'
    | '/work/$slug'
    | '/capabilities/'
    | '/ecosystem/'
    | '/insights/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  EcosystemSlugRoute: typeof EcosystemSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
  EcosystemIndexRoute: typeof EcosystemIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/': {
      id: '/ecosystem/'
      path: '/ecosystem'
      fullPath: '/ecosystem/'
      preLoaderRoute: typeof EcosystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/$slug': {
      id: '/ecosystem/$slug'
      path: '/ecosystem/$slug'
      fullPath: '/ecosystem/$slug'
      preLoaderRoute: typeof EcosystemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  EcosystemSlugRoute: EcosystemSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
  EcosystemIndexRoute: EcosystemIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
